version: "3.9"
   
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: twidder
      MYSQL_DATABASE: twidder
      MYSQL_USER: twidder
      MYSQL_PASSWORD: twidder
  api:
    build: .
    restart: on-failure
    command: /bin/twidder
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment: 
      GIN_MODE: debug
      PORT: 8080
      JWT_SECRET_KEY: secret_key
      MYSQL_DSN: twidder:twidder@tcp(db:3306)/twidder?charset=utf8&parseTime=True
      MAX_IDLE_CONNECTIONS: 10
      MAX_OPEN_CONNECTIONS: 100
      CONNECTION_MAX_LIFETIME_MINUTES: 60
volumes:
  db_data: {}
