version: "3.9"
   
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gin_twitter
      MYSQL_DATABASE: gin_twitter
      MYSQL_USER: gin_twitter
      MYSQL_PASSWORD: gin_twitter
  api:
    build: .
    restart: on-failure
    command: /bin/gin_twitter
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment: 
        GIN_MODE: debug
        PORT: 8080
        JWT_SECRET_KEY: secret_key
        MYSQL_DSN: gin_twitter:gin_twitter@tcp(db:3306)/gin_twitter?charset=utf8&parseTime=True
volumes:
  db_data: {}
